// IKEA India Product Catalog Dataset
const PRODUCTS_DATA = [
  {
    id: "ikea-001",
    name: "STRANDMON",
    category: "Living Room",
    subCategory: "Armchairs",
    type: "Wing chair",
    price: 18990,
    originalPrice: 21990,
    ikeaFamilyPrice: 16990,
    isIkeaFamily: true,
    isNew: false,
    isBestseller: true,
    rating: 4.8,
    reviewsCount: 342,
    badge: "Special Offer",
    colors: ["#1e3a5f", "#3c503c", "#f3e5ab", "#333333"],
    selectedColor: "Nordvalla dark grey",
    description: "You can really loosen up and relax in comfort because the high back on this chair provides extra support for your neck.",
    dimensions: "82x96x101 cm",
    material: "100% polyester fabric, Solid beech frame, Polyurethane foam",
    stockStatus: "In Stock",
    stores: ["Navi Mumbai", "Hyderabad", "Bengaluru", "Worli"],
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80",
    tags: ["living room", "chair", "armchair", "seating", "strandmon"]
  },
  {
    id: "ikea-002",
    name: "BILLY",
    category: "Storage",
    subCategory: "Bookcases",
    type: "Bookcase with glass doors",
    price: 7990,
    originalPrice: 8990,
    ikeaFamilyPrice: 6990,
    isIkeaFamily: true,
    isNew: false,
    isBestseller: true,
    rating: 4.9,
    reviewsCount: 819,
    badge: "Top Seller",
    colors: ["#ffffff", "#2b1e17", "#d9b382"],
    selectedColor: "White",
    description: "It is estimated that every 5 seconds, one BILLY bookcase is sold somewhere in the world. Pretty impressive considering we launched BILLY in 1979.",
    dimensions: "80x28x202 cm",
    material: "Particleboard, Paper foil, Plastic edging",
    stockStatus: "In Stock",
    stores: ["Navi Mumbai", "Hyderabad", "Bengaluru", "Worli", "R City"],
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80",
    tags: ["storage", "bookcase", "shelving", "living room", "billy"]
  },
  {
    id: "ikea-003",
    name: "MALM",
    category: "sofaroom",
    subCategory: "sofas",
    type: "sofa frame, high, with 2 storage boxes",
    price: 24990,
    originalPrice: 27990,
    ikeaFamilyPrice: 22990,
    isIkeaFamily: true,
    isNew: false,
    isBestseller: true,
    rating: 4.7,
    reviewsCount: 512,
    badge: "Great Value",
    colors: ["#ffffff", "#3b2f2f", "#d2b48c"],
    selectedColor: "White stained oak veneer",
    description: "A clean design that’s just as beautiful on all sides – place the sofa freestanding or with the headboard against a wall. Generous storage drawers glide quietly.",
    dimensions: "180x200 cm (King Size)",
    material: "Particleboard, Solid wood veneer, Clear acrylic lacquer",
    stockStatus: "In Stock",
    stores: ["Navi Mumbai", "Hyderabad", "Bengaluru"],
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    tags: ["sofaroom", "sofa", "storage", "king size", "malm"]
  },
  {
    id: "ikea-004",
    name: "KALLAX",
    category: "Storage",
    subCategory: "Shelving units",
    type: "Shelving unit, 4x4 squares",
    price: 9990,
    originalPrice: 11490,
    ikeaFamilyPrice: null,
    isIkeaFamily: false,
    isNew: true,
    isBestseller: true,
    rating: 4.9,
    reviewsCount: 624,
    badge: "New Lower Price",
    colors: ["#ffffff", "#1a1a1a", "#9c7c58"],
    selectedColor: "High-gloss white",
    description: "Standing or lying – the KALLAX series adapts to taste, space, budget and needs. Fine-tune with drawers, shelves, boxes and inserts.",
    dimensions: "147x147 cm",
    material: "Particleboard, Fibreboard, Acrylic paint, Honeycomb structure paper filling",
    stockStatus: "In Stock",
    stores: ["Navi Mumbai", "Hyderabad", "Bengaluru", "Worli"],
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80",
    tags: ["storage", "kallax", "organizer", "shelf", "cube"]
  },
  {
    id: "ikea-005",
    name: "MICKE",
    category: "Workspace",
    subCategory: "Desks",
    type: "Desk with integrated cable management",
    price: 7490,
    originalPrice: 8490,
    ikeaFamilyPrice: 6790,
    isIkeaFamily: true,
    isNew: false,
    isBestseller: true,
    rating: 4.6,
    reviewsCount: 298,
    badge: "WFH Pick",
    colors: ["#ffffff", "#212121", "#78866b"],
    selectedColor: "White/Anthracite",
    description: "A clean and simple look that fits just about anywhere. You can combine it with other desks or drawer units in the MICKE series to extend your work space.",
    dimensions: "105x50 cm",
    material: "Particleboard, Fibreboard, Steel, Epoxy/polyester powder coating",
    stockStatus: "In Stock",
    stores: ["Navi Mumbai", "Hyderabad", "Bengaluru", "Worli", "R City"],
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80",
    tags: ["workspace", "desk", "wfh", "office", "study", "micke"]
  },
  {
    id: "ikea-006",
    name: "FRIHETEN",
    category: "Living Room",
    subCategory: "sofas",
    type: "Corner sofa-sofa with storage",
    price: 49990,
    originalPrice: 54990,
    ikeaFamilyPrice: 46990,
    isIkeaFamily: true,
    isNew: false,
    isBestseller: true,
    rating: 4.7,
    reviewsCount: 420,
    badge: "Bestseller",
    colors: ["#4a4a4a", "#1b303a", "#be9b7b"],
    selectedColor: "Skiftebo dark grey",
    description: "This sofa converts quickly and easily into a spacious sofa when you remove the back cushions and pull out the underframe. Large storage space under the chaise longue.",
    dimensions: "230x151x66 cm",
    material: "100% polyester, Solid pine, Polyurethane foam 30 kg/cu.m.",
    stockStatus: "In Stock",
    stores: ["Navi Mumbai", "Hyderabad", "Bengaluru"],
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80",
    tags: ["living room", "sofa", "couch", "sofa-sofa", "friheten"]
  },
  {
    id: "ikea-007",
    name: "MARKUS",
    category: "Workspace",
    subCategory: "Chairs",
    type: "Ergonomic office chair with mesh back",
    price: 14990,
    originalPrice: 16990,
    ikeaFamilyPrice: 13490,
    isIkeaFamily: true,
    isNew: false,
    isBestseller: true,
    rating: 4.9,
    reviewsCount: 755,
    badge: "10-Year Warranty",
    colors: ["#1c1c1c", "#5a6b7c"],
    selectedColor: "Glose dark grey",
    description: "Adjust the height and angle of this chair so your working day feels comfortable. The mesh backrest lets air through so you stay cool when the workload increases.",
    dimensions: "62x60x140 cm",
    material: "Full grain leather, Steel, High resilience polyurethane foam",
    stockStatus: "In Stock",
    stores: ["Navi Mumbai", "Hyderabad", "Bengaluru", "Worli"],
    image: "https://images.unsplash.com/photo-1580481077195-72886f4a86f9?auto=format&fit=crop&w=800&q=80",
    tags: ["workspace", "office chair", "ergonomic", "markus", "seating"]
  },
  {
    id: "ikea-008",
    name: "NISSAFORS",
    category: "Kitchen",
    subCategory: "Trolleys & Carts",
    type: "Utility cart with 3 tiers",
    price: 2790,
    originalPrice: 3290,
    ikeaFamilyPrice: null,
    isIkeaFamily: false,
    isNew: true,
    isBestseller: false,
    rating: 4.8,
    reviewsCount: 184,
    badge: "Versatile",
    colors: ["#1a1a1a", "#d9534f", "#ffffff"],
    selectedColor: "Black",
    description: "This trolley fits in the smallest of spaces and can be moved to wherever you need it. Use it as extra storage for all your kitchen utensils, desk accessories or for gloves, keys and mobile phones.",
    dimensions: "50.5x30x83 cm",
    material: "Steel, Powder coating",
    stockStatus: "In Stock",
    stores: ["Navi Mumbai", "Hyderabad", "Bengaluru", "Worli", "R City"],
    image: "https://images.unsplash.com/photo-1590725140246-20acdeb442be?auto=format&fit=crop&w=800&q=80",
    tags: ["kitchen", "cart", "trolley", "storage", "nissafors"]
  },
  {
    id: "ikea-009",
    name: "HEMNES",
    category: "sofaroom",
    subCategory: "Chests of Drawers",
    type: "8-drawer dresser, solid pine",
    price: 29990,
    originalPrice: 32990,
    ikeaFamilyPrice: 27990,
    isIkeaFamily: true,
    isNew: false,
    isBestseller: true,
    rating: 4.7,
    reviewsCount: 388,
    badge: "Solid Wood",
    colors: ["#ffffff", "#2c221e", "#506266"],
    selectedColor: "White stain",
    description: "Traditional style combined with modern function. A quiet, smooth drawer glide, solid sustainable pine wood with natural beauty that ages gracefully.",
    dimensions: "160x96 cm",
    material: "Solid pine, Stain, Clear acrylic lacquer",
    stockStatus: "In Stock",
    stores: ["Navi Mumbai", "Hyderabad", "Bengaluru"],
    image: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=800&q=80",
    tags: ["sofaroom", "storage", "dresser", "drawers", "hemnes"]
  },
  {
    id: "ikea-010",
    name: "FEJKA & GRADVIS",
    category: "Decor",
    subCategory: "Artificial Plants & Vases",
    type: "Potted artificial plant with ceramic fluted planter",
    price: 990,
    originalPrice: 1290,
    ikeaFamilyPrice: 799,
    isIkeaFamily: true,
    isNew: true,
    isBestseller: true,
    rating: 4.9,
    reviewsCount: 920,
    badge: "Trending",
    colors: ["#4e6b4e", "#d8b4a0", "#f0ede6"],
    selectedColor: "Sage Green & Earthenware",
    description: "Lifelike artificial plant that stays just as fresh-looking year after year. Paired with the iconic Scandinavian ribsofa ceramic planter.",
    dimensions: "15 cm pot diameter, 35 cm height",
    material: "Polyethylene plastic, 100% recycled PET, Stoneware glaze",
    stockStatus: "In Stock",
    stores: ["Navi Mumbai", "Hyderabad", "Bengaluru", "Worli", "R City"],
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80",
    tags: ["decor", "plant", "vase", "fejka", "gradvis", "living room"]
  },
  {
    id: "ikea-011",
    name: "TERTIAL",
    category: "Lighting",
    subCategory: "Work Lamps",
    type: "Work lamp with clamp, steel",
    price: 1290,
    originalPrice: 1490,
    ikeaFamilyPrice: null,
    isIkeaFamily: false,
    isNew: false,
    isBestseller: true,
    rating: 4.8,
    reviewsCount: 650,
    badge: "Classic Design",
    colors: ["#2d3748", "#ffffff", "#c5a059"],
    selectedColor: "Dark Grey",
    description: "Classic desk lamp introduced in our range in 1998. The adjustable arm and head make it easy to direct the light where you need it.",
    dimensions: "Max 13W, Shade diameter 17 cm",
    material: "Steel, Epoxy/polyester powder coating",
    stockStatus: "In Stock",
    stores: ["Navi Mumbai", "Hyderabad", "Bengaluru", "Worli", "R City"],
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80",
    tags: ["lighting", "lamp", "desk lamp", "tertial", "workspace"]
  },
  {
    id: "ikea-012",
    name: "FRAKTA",
    category: "Decor",
    subCategory: "Bags & Accessories",
    type: "Iconic blue carrier bag, medium/large",
    price: 99,
    originalPrice: 129,
    ikeaFamilyPrice: null,
    isIkeaFamily: false,
    isNew: false,
    isBestseller: true,
    rating: 5.0,
    reviewsCount: 2400,
    badge: "IKEA Icon",
    colors: ["#0058a3"],
    selectedColor: "IKEA Signature Blue",
    description: "After 30 years in our range, it’s one of the most hardworking bags in the world. Big, strong and carries almost anything.",
    dimensions: "55x37x35 cm (71 L)",
    material: "100% polypropylene, 60% recycled",
    stockStatus: "In Stock",
    stores: ["Navi Mumbai", "Hyderabad", "Bengaluru", "Worli", "R City"],
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
    tags: ["bag", "frakta", "icon", "accessories"]
  }
];

const ROOM_INSPIRATIONS = [
  {
    id: "room-1",
    title: "Calm Scandinavian Living Space",
    subtitle: "Modern aesthetic optimized for urban Indian apartments",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80",
    hotspots: [
      { productId: "ikea-006", top: "58%", left: "45%", title: "FRIHETEN sofa-sofa", price: "₹49,990" },
      { productId: "ikea-010", top: "42%", left: "78%", title: "FEJKA Potted Plant", price: "₹990" },
      { productId: "ikea-002", top: "35%", left: "18%", title: "BILLY Bookcase", price: "₹7,990" }
    ]
  },
  {
    id: "room-2",
    title: "Ergonomic & Productive Home Office",
    subtitle: "Smart cable management and comfortable seating for long workdays",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80",
    hotspots: [
      { productId: "ikea-005", top: "62%", left: "48%", title: "MICKE Desk", price: "₹7,490" },
      { productId: "ikea-007", top: "52%", left: "68%", title: "MARKUS Office Chair", price: "₹14,990" },
      { productId: "ikea-011", top: "38%", left: "32%", title: "TERTIAL Work Lamp", price: "₹1,290" }
    ]
  }
];
